export const api = {
	baseUrl: 'https://test.saas.yunmengzhu.com/help/index',
	contactUnit: '/api/ContactUnit',
	baseArea: '/api/BseArea',
	baseProduct: '/api/BseProduct',
	baseUser: '/api/BaseUser',
	capFee: '/api/CapFee',
	capPayment: '/api/CapPayment',
	capreceipt: '/api/Capreceipt',
	cashAccount: '/api/CashAccount',
	dept: '/api/Dept',
	purPurchaseOrder: '/api/PurPurchaseOrder',
	salesOrder: '/api/SalesOrder',
	token: '/api/Token',
	login: '/api/BseUser/Login',
	ChangePassword:'/api/BseUser/ChangePassword',
	Regist:'/api/BseUser/Regist',
	GetUserInfo:'/api/BseUser/GetUserInfo',
	SaveUserInfo:'/api/BseUser/SaveUserInfo',
	GetUserList:'/api/BseUser/GetUserList',
	SaveUser:'/api/BseUser/SaveUser',
	CustomerSave:'/api/Customer/SaveCustomer',
	MyCashAccount: '/api/CashAccount/Query',
	MyCashAccountCreate: '/api/CashAccount/Create',
	MyCashAccountGet: '/api/CashAccount/Get/',
	MyCashAccountUpdate: '/api/CashAccount/Update',
	UploadImg:'/api/BseUser/UploadImg'
	
}