export const api = {
<<<<<<< HEAD
	 baseUrl: 'https://test.saas.yunmengzhu.com',
	//baseUrl:'https://saas.yunmengzhu.com',
=======
	baseUrl: 'https://test.saas.yunmengzhu.com',
	// baseUrl:'https://saas.yunmengzhu.com',
>>>>>>> fe26294870968f4066aa55ee0dbeb06259fd0e95
	// 正式 wxa9c130058c8210a1 测试:wxd7cad7e258a41c60
	contactUnit: '/api/ContactUnit',
	baseArea: '/api/BseArea',
	baseProduct: '/api/BseProduct',
	baseUser: '/api/BaseUser',
	capFee: '/api/CapFee',
	capPayment: '/api/CapPayment',
	capreceipt: '/api/Capreceipt',
	cashAccount: '/api/CashAccount',
	dept: '/api/Dept',
	purPurchaseOrder: '/api/PurPurchaseOrder',
	report: '/api/Report',
	salesOrder: '/api/SalesOrder',
	stkStock: '/api/StkStock',
	QueryWarningStock:'/api/StkStock/QueryWarningStock',
	QueryInit:'/api/StkStock/QueryInit',
	QueryInventory:'/api/StkStock/QueryInventory',
	token: '/api/Token',
	tokenRefresh:'/api/BseUser/RefreshToken',
	login: '/api/BseUser/Login',
	BindUserOpenId: '/api/BseUser/BindUserOpenId',
	UnbindUserOpenId: '/api/BseUser/UnbindUserOpenId ',
	ChangePassword:'/api/BseUser/ChangePassword',
	ResetPassword:'/api/BseUser/ResetPassword',
	Regist:'/api/BseUser/Regist',
	GetUserInfo:'/api/BseUser/GetUserInfo',
	GetUserInfoByUserId:'/api/BseUser/GetUserInfoByUserId',
	SaveUserInfo:'/api/BseUser/SaveUserInfo',
	SaveUserStatus:'/api/BseUser/SaveUserStatus',
	GetUserList:'/api/BseUser/GetUserList',
	GetRoleList:'api/BseRole/GetRoleList',
	SaveUser:'/api/BseUser/SaveUser',
	CustomerSave:'/api/Customer/SaveCustomer',
	MyCashAccount: '/api/CashAccount/Query',
	MyCashAccountCreate: '/api/CashAccount/Create',
	MyCashAccountGet: '/api/CashAccount/Get/',
	MyCashAccountUpdate: '/api/CashAccount/Update',
	UploadImg:'/api/BseUser/UploadImg',
	GetMyDayLogList:'/api/BseUser/GetMyDayLogList',
	GetOrderList:'/api/SysOrder/GetMyOrderList',
	RefundApply:'/api/SysRefund/RefundApply',
	IntegralExchange:'/api/BseUser/IntegralExchange',
	AddOrder:'/api/SysOrder/AddOrder',
	GetCurrentActivity:'/api/SysActivity/GetCurrentActivity',
	GetMyPromotIntegralList :'/api/BseUser/GetMyPromotIntegralList',
	GetSmsCode:'/api/SysMessage/SendVerificationCode',
	GetProductList:'/api/SysProduct/GetProductList',
	Orderypay:'/api/WeChartPay/OrderPay',
	GetSharePic:'/api/BseUser/GetSharePic/',
	GetRefundList:'/api/SysDictionary/GetSysDictionaryList',
	RefundApply:'/api/SysRefund/RefundApply',
	GetFirstActivePrinter:'/api/Print/GetFirstActivePrinter',
	UnBindPrint:'api/Print/UnBind',
	BindPrint:'api/Print/Bind',
	GetWSYLPrinterList:'/api/Print/GetWSYLPrinterList'
	
}